---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: decker
            image: stevenaldinger/decker:latest
            args:
            - decker
            - /go/bin/examples/example.hcl
          restartPolicy: Never
