---
apiVersion: batch/v1
kind: Job
metadata:
  name: decker
spec:
  template:
    spec:
      containers:
      - name: decker
        image: stevenaldinger/decker:latest
        command: ["decker",  "/go/bin/examples/example.hcl"]
      restartPolicy: Never
